"""add permission drafts

Revision ID: 4d0a4741d1cd
Revises: 5c2cb926985a
Create Date: 2026-08-05 17:19:16.272766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0a4741d1cd'
down_revision: Union[str, Sequence[str], None] = '5c2cb926985a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_drafts',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=30), server_default='student_name', nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=10), nullable=True),
    sa.Column('permission_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('awaiting_confirmation', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("step IN ('student_name', 'class_name', 'permission_type', 'description', 'phone_number', 'confirmation')", name='ck_permission_drafts_step'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_permission_drafts_expires_at'), 'permission_drafts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_permission_drafts_step'), 'permission_drafts', ['step'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_drafts_step'), table_name='permission_drafts')
    op.drop_index(op.f('ix_permission_drafts_expires_at'), table_name='permission_drafts')
    op.drop_table('permission_drafts')
    # ### end Alembic commands ###
