"""add conversation message privacy controls

Revision ID: 5c2cb926985a
Revises: 8a17f5b1b2d3
Create Date: 2026-08-03 18:25:34.906007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2cb926985a'
down_revision: Union[str, Sequence[str], None] = '8a17f5b1b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('storage_policy', sa.String(length=20), server_default='full', nullable=False))
    op.add_column('conversation_messages', sa.Column('contains_sensitive_data', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('conversation_messages', sa.Column('retention_until', sa.DateTime(), nullable=True))
    op.add_column('conversation_messages', sa.Column('redacted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversation_messages_contains_sensitive_data'), 'conversation_messages', ['contains_sensitive_data'], unique=False)
    op.create_index(op.f('ix_conversation_messages_redacted_at'), 'conversation_messages', ['redacted_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_retention_until'), 'conversation_messages', ['retention_until'], unique=False)
    op.create_index(op.f('ix_conversation_messages_storage_policy'), 'conversation_messages', ['storage_policy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_storage_policy'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_retention_until'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_redacted_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_contains_sensitive_data'), table_name='conversation_messages')
    op.drop_column('conversation_messages', 'redacted_at')
    op.drop_column('conversation_messages', 'retention_until')
    op.drop_column('conversation_messages', 'contains_sensitive_data')
    op.drop_column('conversation_messages', 'storage_policy')
    # ### end Alembic commands ###
