"""create teachers subjects and lesson schedules

Revision ID: 9961121f5a53
Revises: bfd81eaa6386
Create Date: 2026-08-02 04:53:53.901341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9961121f5a53'
down_revision: Union[str, Sequence[str], None] = 'bfd81eaa6386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=20), server_default='lesson', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("subject_type IN ('lesson', 'activity', 'break')", name=op.f('ck_subjects_subject_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_subjects_normalized_name'))
    )
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_subjects_subject_type'), 'subjects', ['subject_type'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers'))
    )
    op.create_index(op.f('ix_teachers_is_active'), 'teachers', ['is_active'], unique=False)
    op.create_index(op.f('ix_teachers_normalized_name'), 'teachers', ['normalized_name'], unique=False)
    op.create_table('lesson_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("day IN ('senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu')", name=op.f('ck_lesson_schedules_valid_day')),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_lesson_schedules_valid_time_range')),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], name=op.f('fk_lesson_schedules_school_class_id_school_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lesson_schedules_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_lesson_schedules_teacher_id_teachers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_schedules')),
    sa.UniqueConstraint('source_key', name=op.f('uq_lesson_schedules_source_key'))
    )
    op.create_index('ix_lesson_schedules_class_day_time', 'lesson_schedules', ['school_class_id', 'day', 'start_time'], unique=False)
    op.create_index(op.f('ix_lesson_schedules_is_active'), 'lesson_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_lesson_schedules_school_class_id'), 'lesson_schedules', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_lesson_schedules_subject_id'), 'lesson_schedules', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lesson_schedules_teacher_id'), 'lesson_schedules', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_schedules_teacher_id'), table_name='lesson_schedules')
    op.drop_index(op.f('ix_lesson_schedules_subject_id'), table_name='lesson_schedules')
    op.drop_index(op.f('ix_lesson_schedules_school_class_id'), table_name='lesson_schedules')
    op.drop_index(op.f('ix_lesson_schedules_is_active'), table_name='lesson_schedules')
    op.drop_index('ix_lesson_schedules_class_day_time', table_name='lesson_schedules')
    op.drop_table('lesson_schedules')
    op.drop_index(op.f('ix_teachers_normalized_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_is_active'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_subject_type'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
