"""create academic years and school classes

Revision ID: bfd81eaa6386
Revises: 
Create Date: 2026-08-02 04:27:32.030597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd81eaa6386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=9), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date < end_date', name=op.f('ck_academic_years_date_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('name', name=op.f('uq_academic_years_name'))
    )
    op.create_index(op.f('ix_academic_years_is_active'), 'academic_years', ['is_active'], unique=False)
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=3), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("group_letter BETWEEN 'A' AND 'K'", name=op.f('ck_school_classes_group_letter_range')),
    sa.CheckConstraint('grade BETWEEN 7 AND 9', name=op.f('ck_school_classes_grade_range')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_school_classes_academic_year_id_academic_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_classes')),
    sa.UniqueConstraint('academic_year_id', 'class_name', name='uq_school_classes_year_class')
    )
    op.create_index(op.f('ix_school_classes_academic_year_id'), 'school_classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_school_classes_is_active'), 'school_classes', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_classes_is_active'), table_name='school_classes')
    op.drop_index(op.f('ix_school_classes_academic_year_id'), table_name='school_classes')
    op.drop_table('school_classes')
    op.drop_index(op.f('ix_academic_years_is_active'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
