"""add permission requests

Revision ID: d3decac2abae
Revises: de60f0cc1b57
Create Date: 2026-08-04 20:30:48.337011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3decac2abae'
down_revision: Union[str, Sequence[str], None] = 'de60f0cc1b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_code', sa.String(length=32), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('permission_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], name=op.f('fk_permission_requests_school_class_id_school_classes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_requests')),
    sa.UniqueConstraint('source_key', name='uq_permission_requests_source_key'),
    sa.UniqueConstraint('tracking_code', name='uq_permission_requests_tracking_code')
    )
    op.create_index(op.f('ix_permission_requests_class_name'), 'permission_requests', ['class_name'], unique=False)
    op.create_index(op.f('ix_permission_requests_permission_type'), 'permission_requests', ['permission_type'], unique=False)
    op.create_index(op.f('ix_permission_requests_school_class_id'), 'permission_requests', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_permission_requests_status'), 'permission_requests', ['status'], unique=False)
    op.create_index(op.f('ix_permission_requests_submitted_at'), 'permission_requests', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_requests_submitted_at'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_status'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_school_class_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_permission_type'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_class_name'), table_name='permission_requests')
    op.drop_table('permission_requests')
    # ### end Alembic commands ###
