"""add extracurricular tables

Revision ID: de60f0cc1b57
Revises: 9961121f5a53
Create Date: 2026-08-03 22:43:24.993363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de60f0cc1b57'
down_revision: Union[str, Sequence[str], None] = '9961121f5a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracurriculars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('advisor_teacher_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_teacher_id'], ['teachers.id'], name=op.f('fk_extracurriculars_advisor_teacher_id_teachers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracurriculars')),
    sa.UniqueConstraint('normalized_name', name='uq_extracurriculars_normalized_name'),
    sa.UniqueConstraint('source_key', name=op.f('uq_extracurriculars_source_key'))
    )
    op.create_index(op.f('ix_extracurriculars_advisor_teacher_id'), 'extracurriculars', ['advisor_teacher_id'], unique=False)
    op.create_index(op.f('ix_extracurriculars_is_active'), 'extracurriculars', ['is_active'], unique=False)
    op.create_table('extracurricular_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extracurricular_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extracurricular_id'], ['extracurriculars.id'], name=op.f('fk_extracurricular_schedules_extracurricular_id_extracurriculars'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracurricular_schedules')),
    sa.UniqueConstraint('extracurricular_id', 'day', 'start_time', 'end_time', name='uq_extracurricular_schedules_activity_time'),
    sa.UniqueConstraint('source_key', name=op.f('uq_extracurricular_schedules_source_key'))
    )
    op.create_index(op.f('ix_extracurricular_schedules_day'), 'extracurricular_schedules', ['day'], unique=False)
    op.create_index(op.f('ix_extracurricular_schedules_extracurricular_id'), 'extracurricular_schedules', ['extracurricular_id'], unique=False)
    op.create_index(op.f('ix_extracurricular_schedules_is_active'), 'extracurricular_schedules', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracurricular_schedules_is_active'), table_name='extracurricular_schedules')
    op.drop_index(op.f('ix_extracurricular_schedules_extracurricular_id'), table_name='extracurricular_schedules')
    op.drop_index(op.f('ix_extracurricular_schedules_day'), table_name='extracurricular_schedules')
    op.drop_table('extracurricular_schedules')
    op.drop_index(op.f('ix_extracurriculars_is_active'), table_name='extracurriculars')
    op.drop_index(op.f('ix_extracurriculars_advisor_teacher_id'), table_name='extracurriculars')
    op.drop_table('extracurriculars')
    # ### end Alembic commands ###
